### ISSUE TITLE
sso登陆失败 ，之前用的好好的，最近一直失败

### ISSUE THREAD

**Issue by ioi-c** [airbasic/weibo_album_spider#1]
检查了sso登录返回的url，浏览器是可以用的
但是pjs重定向 weibo.cn 没用，总是显示未登录

**Comment by airbasic** [comment]
看了下代码 微博返回的json 的sso url已经自带https: 而不是以前的 //xxx.xxx.xxx/ 所以删除前面的 https: 就好了
